import datetime

from django.db.transaction import commit, rollback, set_autocommit
from tournoi.models import Club, Fixture, Game


SEASON = [({'day': 8,
            'month': 8,
            'hh': 19,
            'mm': 30,
            'home': 'SR',
            'visitors': 'PSG',
            'hscore': 2,
            'vscore': 2},

           {'day': 9,
            'month': 8,
            'hh': 20,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'SMC',
            'hscore': 0,
            'vscore': 3},

           {'day': 9,
            'month': 8,
            'hh': 20,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'ASSE',
            'hscore': 0,
            'vscore': 2},

           {'day': 9,
            'month': 8,
            'hh': 20,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'FCM',
            'hscore': 0,
            'vscore': 0},

           {'day': 9,
            'month': 8,
            'hh': 20,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'FCGB',
            'hscore': 0,
            'vscore': 1},

           {'day': 9,
            'month': 8,
            'hh': 20,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'RCL',
            'hscore': 1,
            'vscore': 0},

           {'day': 9,
            'month': 8,
            'hh': 20,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'TFC',
            'hscore': 3,
            'vscore': 2},

           {'day': 9,
            'month': 8,
            'hh': 20,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'OM',
            'hscore': 3,
            'vscore': 3},

           {'day': 10,
            'month': 8,
            'hh': 16,
            'mm': 00,
            'home': 'OL',
            'visitors': 'SRFC',
            'hscore': 2,
            'vscore': 0},

           {'day': 10,
            'month': 8,
            'hh': 20,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'FCL',
            'hscore': 1,
            'vscore': 2}),

          ({'day': 15,
            'month': 8,
            'hh': 19,
            'mm': 30,
            'home': 'SMC',
            'visitors': 'LOSC',
            'hscore': 0,
            'vscore': 1},

           {'day': 16,
            'month': 8,
            'hh': 16,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'SCB',
            'hscore': 2,
            'vscore': 0},

           {'day': 16,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'OL',
            'hscore': 2,
            'vscore': 1},

           {'day': 16,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'FCN',
            'hscore': 1,
            'vscore': 1},

           {'day': 16,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'OGCN',
            'hscore': 0,
            'vscore': 0},

           {'day': 16,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'EAG',
            'hscore': 0,
            'vscore': 1},

           {'day': 16,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'ETG',
            'hscore': 6,
            'vscore': 2},

           {'day': 17,
            'month': 8,
            'hh': 16,
            'mm': 00,
            'home': 'OM',
            'visitors': 'MHSC',
            'hscore': 0,
            'vscore': 2},

           {'day': 17,
            'month': 8,
            'hh': 16,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'SR',
            'hscore': 3,
            'vscore': 1},

           {'day': 17,
            'month': 8,
            'hh': 20,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'ASM',
            'hscore': 4,
            'vscore': 1}),

          ({'day': 22,
            'month': 8,
            'hh': 19,
            'mm': 30,
            'home': 'ETG',
            'visitors': 'PSG',
            'hscore': 0,
            'vscore': 0},

           {'day': 23,
            'month': 8,
            'hh': 16,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'OM',
            'hscore': 0,
            'vscore': 1},

           {'day': 23,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'FCGB',
            'hscore': 1,
            'vscore': 3},

           {'day': 23,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'SR',
            'visitors': 'SMC',
            'hscore': 0,
            'vscore': 2},

           {'day': 23,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'TFC',
            'hscore': 1,
            'vscore': 0},

           {'day': 23,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'FCL',
            'hscore': 2,
            'vscore': 0},

           {'day': 23,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'FCM',
            'hscore': 2,
            'vscore': 0},

           {'day': 24,
            'month': 8,
            'hh': 13,
            'mm': 00,
            'home': 'OL',
            'visitors': 'RCL',
            'hscore': 0,
            'vscore': 1},

           {'day': 24,
            'month': 8,
            'hh': 16,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'SRFC',
            'hscore': 0,
            'vscore': 0},

           {'day': 24,
            'month': 8,
            'hh': 20,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'ASM',
            'hscore': 0,
            'vscore': 1}),

          ({'day': 29,
            'month': 8,
            'hh': 19,
            'mm': 30,
            'home': 'OM',
            'visitors': 'OGCN',
            'hscore': 4,
            'vscore': 0},

           {'day': 30,
            'month': 8,
            'hh': 16,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'LOSC',
            'hscore': 1,
            'vscore': 1},

           {'day': 30,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'MHSC',
            'hscore': 1,
            'vscore': 0},

           {'day': 30,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'SR',
            'hscore': 4,
            'vscore': 2},

           {'day': 30,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'SRFC',
            'hscore': 0,
            'vscore': 1},

           {'day': 30,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'EAG',
            'hscore': 4,
            'vscore': 0},

           {'day': 30,
            'month': 8,
            'hh': 19,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'ETG',
            'hscore': 1,
            'vscore': 0},

           {'day': 31,
            'month': 8,
            'hh': 13,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'SCB',
            'hscore': 1,
            'vscore': 1},

           {'day': 31,
            'month': 8,
            'hh': 16,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'OL',
            'hscore': 2,
            'vscore': 1},

           {'day': 31,
            'month': 8,
            'hh': 20,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'ASSE',
            'hscore': 5,
            'vscore': 0}),

          ({'day': 12,
            'month': 9,
            'hh': 19,
            'mm': 30,
            'home': 'OL',
            'visitors': 'ASM',
            'hscore': 2,
            'vscore': 1},

           {'day': 13,
            'month': 9,
            'hh': 16,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'PSG',
            'hscore': 1,
            'vscore': 1},

           {'day': 13,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'FCM',
            'hscore': 1,
            'vscore': 0},

           {'day': 13,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'SMC',
            'hscore': 1,
            'vscore': 0},

           {'day': 13,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'RCL',
            'hscore': 1,
            'vscore': 1},

           {'day': 13,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'SR',
            'visitors': 'TFC',
            'hscore': 2,
            'vscore': 0},

           {'day': 13,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'FCL',
            'hscore': 1,
            'vscore': 0},

           {'day': 14,
            'month': 9,
            'hh': 13,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'FCN',
            'hscore': 2,
            'vscore': 0},

           {'day': 14,
            'month': 9,
            'hh': 16,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'FCGB',
            'hscore': 2,
            'vscore': 1},

           {'day': 14,
            'month': 9,
            'hh': 20,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'OM',
            'hscore': 1,
            'vscore': 3}),

          ({'day': 19,
            'month': 9,
            'hh': 19,
            'mm': 30,
            'home': 'FCGB',
            'visitors': 'ETG',
            'hscore': 2,
            'vscore': 1},

           {'day': 20,
            'month': 9,
            'hh': 16,
            'mm': 00,
            'home': 'OM',
            'visitors': 'SRFC',
            'hscore': 3,
            'vscore': 0},

           {'day': 20,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'SR',
            'hscore': 0,
            'vscore': 1},

           {'day': 20,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'SCB',
            'hscore': 3,
            'vscore': 1},

           {'day': 20,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'OGCN',
            'hscore': 2,
            'vscore': 1},

           {'day': 20,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'SMC',
            'hscore': 3,
            'vscore': 3},

           {'day': 21,
            'month': 9,
            'hh': 13,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'MHSC',
            'hscore': 0,
            'vscore': 0},

           {'day': 21,
            'month': 9,
            'hh': 16,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'EAG',
            'hscore': 1,
            'vscore': 0},

           {'day': 21,
            'month': 9,
            'hh': 16,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'ASSE',
            'hscore': 0,
            'vscore': 1},

           {'day': 21,
            'month': 9,
            'hh': 20,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'OL',
            'hscore': 1,
            'vscore': 1}),

          ({'day': 23,
            'month': 9,
            'hh': 18,
            'mm': 00,
            'home': 'SR',
            'visitors': 'OM',
            'hscore': 0,
            'vscore': 5},

           {'day': 23,
            'month': 9,
            'hh': 20,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'TFC',
            'hscore': 0,
            'vscore': 3},

           {'day': 24,
            'month': 9,
            'hh': 18,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'FCM',
            'hscore': 0,
            'vscore': 1},

           {'day': 24,
            'month': 9,
            'hh': 18,
            'mm': 00,
            'home': 'OL',
            'visitors': 'FCL',
            'hscore': 4,
            'vscore': 0},

           {'day': 24,
            'month': 9,
            'hh': 18,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'RCL',
            'hscore': 2,
            'vscore': 1},

           {'day': 24,
            'month': 9,
            'hh': 18,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'LOSC',
            'hscore': 1,
            'vscore': 0},

           {'day': 24,
            'month': 9,
            'hh': 18,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'FCN',
            'hscore': 0,
            'vscore': 0},

           {'day': 24,
            'month': 9,
            'hh': 18,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'ASM',
            'hscore': 0,
            'vscore': 1},

           {'day': 24,
            'month': 9,
            'hh': 20,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'PSG',
            'hscore': 0,
            'vscore': 2},

           {'day': 25,
            'month': 9,
            'hh': 20,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'FCGB',
            'hscore': 1,
            'vscore': 1}),

          ({'day': 27,
            'month': 9,
            'hh': 13,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'OGCN',
            'hscore': 0,
            'vscore': 1},

           {'day': 27,
            'month': 9,
            'hh': 16,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'PSG',
            'hscore': 1,
            'vscore': 1},

           {'day': 27,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'EAG',
            'hscore': 2,
            'vscore': 1},

           {'day': 27,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'SCB',
            'hscore': 1,
            'vscore': 0},

           {'day': 27,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'ETG',
            'hscore': 0,
            'vscore': 2},

           {'day': 27,
            'month': 9,
            'hh': 19,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'SR',
            'hscore': 3,
            'vscore': 0},

           {'day': 28,
            'month': 9,
            'hh': 13,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'SRFC',
            'hscore': 2,
            'vscore': 1},

           {'day': 28,
            'month': 9,
            'hh': 16,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'OL',
            'hscore': 1,
            'vscore': 1},

           {'day': 28,
            'month': 9,
            'hh': 16,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'SMC',
            'hscore': 0,
            'vscore': 0},

           {'day': 28,
            'month': 9,
            'hh': 20,
            'mm': 00,
            'home': 'OM',
            'visitors': 'ASSE',
            'hscore': 2,
            'vscore': 1}),

          ({'day': 3,
            'month': 10,
            'hh': 19,
            'mm': 30,
            'home': 'SR',
            'visitors': 'FCGB',
            'hscore': 1,
            'vscore': 0},

           {'day': 4,
            'month': 10,
            'hh': 16,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'OM',
            'hscore': 1,
            'vscore': 2},

           {'day': 4,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'FCL',
            'hscore': 0,
            'vscore': 2},

           {'day': 4,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'MHSC',
            'hscore': 1,
            'vscore': 1},

           {'day': 4,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'RCL',
            'hscore': 2,
            'vscore': 0},

           {'day': 4,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'FCM',
            'hscore': 3,
            'vscore': 0},

           {'day': 5,
            'month': 10,
            'hh': 13,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'TFC',
            'hscore': 0,
            'vscore': 1},

           {'day': 5,
            'month': 10,
            'hh': 16,
            'mm': 00,
            'home': 'OL',
            'visitors': 'LOSC',
            'hscore': 3,
            'vscore': 0},

           {'day': 5,
            'month': 10,
            'hh': 16,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'FCN',
            'hscore': 0,
            'vscore': 1},

           {'day': 5,
            'month': 10,
            'hh': 20,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'ASM',
            'hscore': 1,
            'vscore': 1}),

          ({'day': 17,
            'month': 10,
            'hh': 19,
            'mm': 30,
            'home': 'RCL',
            'visitors': 'PSG',
            'hscore': 1,
            'vscore': 3},

           {'day': 18,
            'month': 10,
            'hh': 16,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'ASSE',
            'hscore': 0,
            'vscore': 1},

           {'day': 18,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'SCB',
            'hscore': 0,
            'vscore': 1},

           {'day': 18,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'SRFC',
            'hscore': 0,
            'vscore': 0},

           {'day': 18,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'ETG',
            'hscore': 2,
            'vscore': 0},

           {'day': 18,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'SR',
            'hscore': 1,
            'vscore': 1},

           {'day': 18,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'EAG',
            'hscore': 1,
            'vscore': 2},

           {'day': 19,
            'month': 10,
            'hh': 13,
            'mm': 00,
            'home': 'OM',
            'visitors': 'TFC',
            'hscore': 2,
            'vscore': 0},

           {'day': 19,
            'month': 10,
            'hh': 16,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'SMC',
            'hscore': 1,
            'vscore': 1},

           {'day': 19,
            'month': 10,
            'hh': 20,
            'mm': 00,
            'home': 'OL',
            'visitors': 'MHSC',
            'hscore': 5,
            'vscore': 1}),

          ({'day': 24,
            'month': 10,
            'hh': 19,
            'mm': 30,
            'home': 'TFC',
            'visitors': 'RCL',
            'hscore': 0,
            'vscore': 2},

           {'day': 25,
            'month': 10,
            'hh': 16,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'FCGB',
            'hscore': 3,
            'vscore': 0},

           {'day': 25,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'ASM',
            'hscore': 1,
            'vscore': 3},

           {'day': 25,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'FCL',
            'hscore': 2,
            'vscore': 1},

           {'day': 25,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'FCN',
            'hscore': 0,
            'vscore': 2},

           {'day': 25,
            'month': 10,
            'hh': 19,
            'mm': 00,
            'home': 'SR',
            'visitors': 'MHSC',
            'hscore': 1,
            'vscore': 0},

           {'day': 26,
            'month': 10,
            'hh': 14,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'LOSC',
            'hscore': 2,
            'vscore': 0},

           {'day': 26,
            'month': 10,
            'hh': 17,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'OGCN',
            'hscore': 2,
            'vscore': 7},

           {'day': 26,
            'month': 10,
            'hh': 17,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'FCM',
            'hscore': 1,
            'vscore': 0},

           {'day': 26,
            'month': 10,
            'hh': 21,
            'mm': 00,
            'home': 'OL',
            'visitors': 'OM',
            'hscore': 1,
            'vscore': 0}),

          ({'day': 31,
            'month': 10,
            'hh': 20,
            'mm': 30,
            'home': 'ASM',
            'visitors': 'SR',
            'hscore': 1,
            'vscore': 1},

           {'day': 1,
            'month': 11,
            'hh': 17,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'PSG',
            'hscore': 1,
            'vscore': 2},

           {'day': 1,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'OL',
            'hscore': 1,
            'vscore': 3},

           {'day': 1,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'ETG',
            'hscore': 2,
            'vscore': 0},

           {'day': 1,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'ASSE',
            'hscore': 1,
            'vscore': 1},

           {'day': 1,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'SCB',
            'hscore': 1,
            'vscore': 0},

           {'day': 1,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'SMC',
            'hscore': 3,
            'vscore': 2},

           {'day': 2,
            'month': 11,
            'hh': 14,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'SRFC',
            'hscore': 1,
            'vscore': 1},

           {'day': 2,
            'month': 11,
            'hh': 17,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'TFC',
            'hscore': 2,
            'vscore': 1},

           {'day': 2,
            'month': 11,
            'hh': 21,
            'mm': 00,
            'home': 'OM',
            'visitors': 'RCL',
            'hscore': 2,
            'vscore': 1}),

          ({'day': 7,
            'month': 11,
            'hh': 20,
            'mm': 30,
            'home': 'SRFC',
            'visitors': 'FCL',
            'hscore': 1,
            'vscore': 0},

           {'day': 8,
            'month': 11,
            'hh': 17,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'FCGB',
            'hscore': 1,
            'vscore': 2},

           {'day': 8,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'FCN',
            'hscore': 1,
            'vscore': 2},

           {'day': 8,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'OGCN',
            'hscore': 1,
            'vscore': 0},

           {'day': 8,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'MHSC',
            'hscore': 2,
            'vscore': 0},

           {'day': 8,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'FCM',
            'hscore': 3,
            'vscore': 0},

           {'day': 9,
            'month': 11,
            'hh': 14,
            'mm': 00,
            'home': 'OL',
            'visitors': 'EAG',
            'hscore': 3,
            'vscore': 1},

           {'day': 9,
            'month': 11,
            'hh': 17,
            'mm': 00,
            'home': 'SR',
            'visitors': 'LOSC',
            'hscore': 2,
            'vscore': 0},

           {'day': 9,
            'month': 11,
            'hh': 17,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'ASM',
            'hscore': 1,
            'vscore': 1},

           {'day': 9,
            'month': 11,
            'hh': 21,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'OM',
            'hscore': 2,
            'vscore': 0}),

          ({'day': 21,
            'month': 11,
            'hh': 20,
            'mm': 30,
            'home': 'FCM',
            'visitors': 'PSG',
            'hscore': 2,
            'vscore': 3},

           {'day': 22,
            'month': 11,
            'hh': 17,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'OL',
            'hscore': 0,
            'vscore': 0},

           {'day': 22,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'SMC',
            'hscore': 2,
            'vscore': 2},

           {'day': 22,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'SR',
            'hscore': 0,
            'vscore': 0},

           {'day': 22,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'SRFC',
            'hscore': 0,
            'vscore': 1},

           {'day': 22,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'RCL',
            'hscore': 1,
            'vscore': 0},

           {'day': 23,
            'month': 11,
            'hh': 14,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'ASSE',
            'hscore': 0,
            'vscore': 0},

           {'day': 23,
            'month': 11,
            'hh': 17,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'TFC',
            'hscore': 2,
            'vscore': 0},

           {'day': 23,
            'month': 11,
            'hh': 21,
            'mm': 00,
            'home': 'OM',
            'visitors': 'FCGB',
            'hscore': 3,
            'vscore': 1},

           {'day': 7,
            'month': 1,
            'hh': 18,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'ETG'}),

          ({'day': 28,
            'month': 11,
            'hh': 20,
            'mm': 30,
            'home': 'OM',
            'visitors': 'FCN',
            'hscore': 2,
            'vscore': 0},

           {'day': 29,
            'month': 11,
            'hh': 17,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'OGCN',
            'hscore': 1,
            'vscore': 0},

           {'day': 29,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'SR',
            'visitors': 'SCB',
            'hscore': 2,
            'vscore': 1},

           {'day': 29,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'ASM',
            'hscore': 2,
            'vscore': 0},

           {'day': 29,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'FCL',
            'hscore': 2,
            'vscore': 3},

           {'day': 29,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'FCM',
            'hscore': 2,
            'vscore': 0},

           {'day': 29,
            'month': 11,
            'hh': 20,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'MHSC',
            'hscore': 1,
            'vscore': 1},

           {'day': 30,
            'month': 11,
            'hh': 14,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'LOSC',
            'hscore': 1,
            'vscore': 0},

           {'day': 30,
            'month': 11,
            'hh': 17,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'EAG',
            'hscore': 2,
            'vscore': 0},

           {'day': 30,
            'month': 11,
            'hh': 21,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'OL',
            'hscore': 3,
            'vscore': 0}),

          ({'day': 2,
            'month': 12,
            'hh': 19,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'OM',
            'hscore': 1,
            'vscore': 1},

           {'day': 2,
            'month': 12,
            'hh': 19,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'TFC',
            'hscore': 1,
            'vscore': 2},

           {'day': 2,
            'month': 12,
            'hh': 21,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'RCL',
            'hscore': 2,
            'vscore': 0},

           {'day': 3,
            'month': 12,
            'hh': 19,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'FCGB'},

           {'day': 3,
            'month': 12,
            'hh': 19,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'SRFC'},

           {'day': 3,
            'month': 12,
            'hh': 19,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'ETG'},

           {'day': 3,
            'month': 12,
            'hh': 19,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'SMC'},

           {'day': 3,
            'month': 12,
            'hh': 19,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'ASSE'},

           {'day': 3,
            'month': 12,
            'hh': 21,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'PSG'},

           {'day': 4,
            'month': 12,
            'hh': 21,
            'mm': 00,
            'home': 'OL',
            'visitors': 'SR'}),

          ({'day': 5,
            'month': 12,
            'hh': 20,
            'mm': 30,
            'home': 'TFC',
            'visitors': 'ASM'},

           {'day': 6,
            'month': 12,
            'hh': 17,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'FCN'},

           {'day': 6,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'FCL'},

           {'day': 6,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'SCB'},

           {'day': 6,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'MHSC'},

           {'day': 6,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'OGCN'},

           {'day': 7,
            'month': 12,
            'hh': 14,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'OL'},

           {'day': 7,
            'month': 12,
            'hh': 17,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'LOSC'},

           {'day': 7,
            'month': 12,
            'hh': 17,
            'mm': 00,
            'home': 'SR',
            'visitors': 'EAG'},

           {'day': 7,
            'month': 12,
            'hh': 21,
            'mm': 00,
            'home': 'OM',
            'visitors': 'FCM'}),

          ({'day': 12,
            'month': 12,
            'hh': 20,
            'mm': 30,
            'home': 'OL',
            'visitors': 'SMC'},

           {'day': 13,
            'month': 12,
            'hh': 17,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'FCGB'},

           {'day': 13,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'SRFC'},

           {'day': 13,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'SR',
            'visitors': 'ETG'},

           {'day': 13,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'RCL'},

           {'day': 13,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'FCM'},

           {'day': 14,
            'month': 12,
            'hh': 14,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'ASSE'},

           {'day': 14,
            'month': 12,
            'hh': 17,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'TFC'},

           {'day': 14,
            'month': 12,
            'hh': 17,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'PSG'},

           {'day': 14,
            'month': 12,
            'hh': 21,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'OM'}),

          ({'day': 19,
            'month': 12,
            'hh': 20,
            'mm': 30,
            'home': 'RCL',
            'visitors': 'OGCN'},

           {'day': 20,
            'month': 12,
            'hh': 17,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'MHSC'},

           {'day': 20,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'SCB'},

           {'day': 20,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'SR'},

           {'day': 20,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'FCN'},

           {'day': 20,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'EAG'},

           {'day': 20,
            'month': 12,
            'hh': 20,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'ASM'},

           {'day': 21,
            'month': 12,
            'hh': 14,
            'mm': 00,
            'home': 'OM',
            'visitors': 'LOSC'},

           {'day': 21,
            'month': 12,
            'hh': 17,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'ETG'},

           {'day': 21,
            'month': 12,
            'hh': 21,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'OL'}),

          ({'day': 10,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'FCL'},

           {'day': 10,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'SMC'},

           {'day': 10,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'SR',
            'visitors': 'ASSE'},

           {'day': 10,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'PSG'},

           {'day': 10,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'FCM'},

           {'day': 10,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'OM'},

           {'day': 10,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'RCL'},

           {'day': 10,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'SRFC'},

           {'day': 10,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'OL',
            'visitors': 'TFC'},

           {'day': 10,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'FCGB'}),

          ({'day': 17,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'ETG'},

           {'day': 17,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'MHSC'},

           {'day': 17,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'FCN'},

           {'day': 17,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'OGCN'},

           {'day': 17,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'SCB'},

           {'day': 17,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'OM',
            'visitors': 'EAG'},

           {'day': 17,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'ASSE'},

           {'day': 17,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'LOSC'},

           {'day': 17,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'SR'},

           {'day': 17,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'OL'}),

          ({'day': 24,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'FCGB'},

           {'day': 24,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'FCL'},

           {'day': 24,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'PSG'},

           {'day': 24,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'SR',
            'visitors': 'RCL'},

           {'day': 24,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'ASM'},

           {'day': 24,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'FCN'},

           {'day': 24,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'TFC'},

           {'day': 24,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'OL',
            'visitors': 'FCM'},

           {'day': 24,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'SMC'},

           {'day': 24,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'OM'}),

          ({'day': 31,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'OM',
            'visitors': 'ETG'},

           {'day': 31,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'OL'},

           {'day': 31,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'EAG'},

           {'day': 31,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'SR'},

           {'day': 31,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'OGCN'},

           {'day': 31,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'MHSC'},

           {'day': 31,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'SRFC'},

           {'day': 31,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'SCB'},

           {'day': 31,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'ASSE'},

           {'day': 31,
            'month': 1,
            'hh': 20,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'LOSC'}),

          ({'day': 7,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'FCM'},

           {'day': 7,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'RCL'},

           {'day': 7,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'OM'},

           {'day': 7,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'ASM'},

           {'day': 7,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'SR',
            'visitors': 'FCL'},

           {'day': 7,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'LOSC'},

           {'day': 7,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'OL',
            'visitors': 'PSG'},

           {'day': 7,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'FCGB'},

           {'day': 7,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'FCN'},

           {'day': 7,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'TFC'}),

          ({'day': 14,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'OGCN'},

           {'day': 14,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'MHSC'},

           {'day': 14,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'ASSE'},

           {'day': 14,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'SRFC'},

           {'day': 14,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'OM',
            'visitors': 'SR'},

           {'day': 14,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'ETG'},

           {'day': 14,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'SMC'},

           {'day': 14,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'EAG'},

           {'day': 14,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'OL'},

           {'day': 14,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'SCB'}),

          ({'day': 21,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'OL',
            'visitors': 'FCN'},

           {'day': 21,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'SR',
            'visitors': 'FCM'},

           {'day': 21,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'OM'},

           {'day': 21,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'ASM'},

           {'day': 21,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'LOSC'},

           {'day': 21,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'FCGB'},

           {'day': 21,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'RCL'},

           {'day': 21,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'TFC'},

           {'day': 21,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'FCL'},

           {'day': 21,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'MHSC'}),

          ({'day': 28,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'SR'},

           {'day': 28,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'SCB'},

           {'day': 28,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'PSG'},

           {'day': 28,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'ASSE'},

           {'day': 28,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'EAG'},

           {'day': 28,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'OM',
            'visitors': 'SMC'},

           {'day': 28,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'SRFC'},

           {'day': 28,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'OL'},

           {'day': 28,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'ETG'},

           {'day': 28,
            'month': 2,
            'hh': 20,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'OGCN'}),

          ({'day': 7,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'FCM'},

           {'day': 7,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'FCL'},

           {'day': 7,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'SR',
            'visitors': 'FCN'},

           {'day': 7,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'ASM'},

           {'day': 7,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'FCGB'},

           {'day': 7,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'OGCN'},

           {'day': 7,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'RCL'},

           {'day': 7,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'LOSC'},

           {'day': 7,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'OM'},

           {'day': 7,
            'month': 3,
            'hh': 21,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'OL'}),

          ({'day': 14,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'PSG'},

           {'day': 14,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'EAG'},

           {'day': 14,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'ETG'},

           {'day': 14,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'SCB'},

           {'day': 14,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'SRFC'},

           {'day': 14,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'TFC'},

           {'day': 14,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'ASSE'},

           {'day': 14,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'SMC'},

           {'day': 14,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'SR'},

           {'day': 14,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'OM',
            'visitors': 'OL'}),

          ({'day': 21,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'OM'},

           {'day': 21,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'LOSC'},

           {'day': 21,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'SR',
            'visitors': 'ASM'},

           {'day': 21,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'FCGB'},

           {'day': 21,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'EAG'},

           {'day': 21,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'OL',
            'visitors': 'OGCN'},

           {'day': 21,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'MHSC'},

           {'day': 21,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'FCL'},

           {'day': 21,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'FCM'},

           {'day': 21,
            'month': 3,
            'hh': 20,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'FCN'}),

          ({'day': 4,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'SCB'},

           {'day': 4,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'RCL'},

           {'day': 4,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'ASSE'},

           {'day': 4,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'ETG'},

           {'day': 4,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'SMC'},

           {'day': 4,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'SRFC'},

           {'day': 4,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'SR'},

           {'day': 4,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'OL'},

           {'day': 4,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'TFC'},

           {'day': 4,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'OM',
            'visitors': 'PSG'}),

          ({'day': 12,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'EAG'},

           {'day': 12,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'OL',
            'visitors': 'SCB'},

           {'day': 12,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'SR',
            'visitors': 'OGCN'},

           {'day': 12,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'ASM'},

           {'day': 12,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'MHSC'},

           {'day': 12,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'FCN'},

           {'day': 12,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'FCL'},

           {'day': 12,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'LOSC'},

           {'day': 12,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'FCM'},

           {'day': 12,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'OM'}),

          ({'day': 18,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'SMC'},

           {'day': 18,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'SR'},

           {'day': 18,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'SRFC'},

           {'day': 18,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'PSG'},

           {'day': 18,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'OM'},

           {'day': 18,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'RCL'},

           {'day': 18,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'FCGB'},

           {'day': 18,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'OL',
            'visitors': 'ASSE'},

           {'day': 18,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'ETG'},

           {'day': 18,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'TFC'}),

          ({'day': 25,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'FCM'},

           {'day': 25,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'SR',
            'visitors': 'OL'},

           {'day': 25,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'SCB'},

           {'day': 25,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'ASM'},

           {'day': 25,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'MHSC'},

           {'day': 25,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'OGCN'},

           {'day': 25,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'LOSC'},

           {'day': 25,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'EAG'},

           {'day': 25,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'FCN'},

           {'day': 25,
            'month': 4,
            'hh': 19,
            'mm': 00,
            'home': 'OM',
            'visitors': 'FCL'}),

          ({'day': 2,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'RCL'},

           {'day': 2,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'TFC'},

           {'day': 2,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'ASSE'},

           {'day': 2,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'SMC'},

           {'day': 2,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'PSG'},

           {'day': 2,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'OM'},

           {'day': 2,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'OL',
            'visitors': 'ETG'},

           {'day': 2,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'FCGB'},

           {'day': 2,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'SR'},

           {'day': 2,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'SRFC'}),

          ({'day': 9,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'MHSC'},

           {'day': 9,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'LOSC'},

           {'day': 9,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'FCN'},

           {'day': 9,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'OGCN'},

           {'day': 9,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'EAG'},

           {'day': 9,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'FCL'},

           {'day': 9,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'SR'},

           {'day': 9,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'OL'},

           {'day': 9,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'OM',
            'visitors': 'ASM'},

           {'day': 9,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'SRFC',
            'visitors': 'SCB'}),

          ({'day': 16,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'OGCN',
            'visitors': 'RCL'},

           {'day': 16,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'SR',
            'visitors': 'SRFC'},

           {'day': 16,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'SCB',
            'visitors': 'SMC'},

           {'day': 16,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'FCN',
            'visitors': 'FCL'},

           {'day': 16,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'LOSC',
            'visitors': 'OM'},

           {'day': 16,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'OL',
            'visitors': 'FCGB'},

           {'day': 16,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'EAG',
            'visitors': 'TFC'},

           {'day': 16,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'ETG',
            'visitors': 'ASSE'},

           {'day': 16,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'MHSC',
            'visitors': 'PSG'},

           {'day': 16,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'ASM',
            'visitors': 'FCM'}),

          ({'day': 23,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'PSG',
            'visitors': 'SR'},

           {'day': 23,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'FCL',
            'visitors': 'ASM'},

           {'day': 23,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'FCGB',
            'visitors': 'MHSC'},

           {'day': 23,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'TFC',
            'visitors': 'OGCN'},

           {'day': 23,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'OM',
            'visitors': 'SCB'},

           {'day': 23,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'RCL',
            'visitors': 'FCN'},

           {'day': 23,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'FCM',
            'visitors': 'LOSC'},

           {'day': 23,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'SMC',
            'visitors': 'ETG'},

           {'day': 23,
            'month': 5,
            'hh': 19,
            'mm': 00,
            'home': 'ASSE',
            'visitors': 'EAG'},

          {'day': 23,
           'month': 5,
           'hh': 19,
           'mm': 00,
           'home': 'SRFC',
           'visitors': 'OL'})]


set_autocommit(False)

try:
    for i, fixture in enumerate(SEASON):
        f = Fixture(season=2014, week=i + 1)
        f.save()

        clubs = set()
        games = 0

        for game in fixture:
            games += 1

            if game['home'] not in clubs:
                clubs.add(game['home'])
                print game['home']
                home = Club.objects.get(shortname=game['home'])
            else:
                raise Exception('week {}, club duplicate {}'.format(i, game['home']))

            if game['visitors'] not in clubs:
                clubs.add(game['visitors'])
                print game['visitors']
                visitors = Club.objects.get(shortname=game['visitors'])
            else:
                raise Exception('week {}, club duplicate {}'.format(i, game['visitors']))

            date = datetime.datetime(year=2014 if game['month'] >= 8 else 2015,
                                     month=game['month'],
                                     day=game['day'],
                                     hour=game['hh'],
                                     minute=game['mm'])

            hscore = game.get('hscore', -1)
            vscore = game.get('vscore', -1)

            g = Game(home=home, visitors=visitors, date=date, fixture=f,
                     hscore=hscore, vscore=vscore)
            g.save()

        if games != 10:
            raise Exception('week {}, missing game(s)'.format(i))

    if i != 37:
        raise Exception('{}'.format(i))

    commit()

except Exception as exc:
    rollback()
    print exc
